# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import currency_pb2 as currency__pb2


class CurrencyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DownloadCurrencies = channel.unary_stream(
        '/Currency/DownloadCurrencies',
        request_serializer=currency__pb2.SubscribedCurrencies.SerializeToString,
        response_deserializer=currency__pb2.CurrencyValue.FromString,
        )


class CurrencyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DownloadCurrencies(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrencyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DownloadCurrencies': grpc.unary_stream_rpc_method_handler(
          servicer.DownloadCurrencies,
          request_deserializer=currency__pb2.SubscribedCurrencies.FromString,
          response_serializer=currency__pb2.CurrencyValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Currency', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
