# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currency.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='currency.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63urrency.proto\"g\n\x14SubscribedCurrencies\x12%\n\x0enativeCurrency\x18\x01 \x01(\x0e\x32\r.CurrencyType\x12(\n\x11\x66oreignCurrencies\x18\x02 \x03(\x0e\x32\r.CurrencyType\"?\n\rCurrencyValue\x12\x1f\n\x08\x63urrency\x18\x01 \x01(\x0e\x32\r.CurrencyType\x12\r\n\x05value\x18\x02 \x01(\x02*)\n\x0c\x43urrencyType\x12\x07\n\x03PLN\x10\x00\x12\x07\n\x03\x45UR\x10\x01\x12\x07\n\x03\x43HF\x10\x02\x32K\n\x08\x43urrency\x12?\n\x12\x44ownloadCurrencies\x12\x15.SubscribedCurrencies\x1a\x0e.CurrencyValue\"\x00\x30\x01\x62\x06proto3')
)

_CURRENCYTYPE = _descriptor.EnumDescriptor(
  name='CurrencyType',
  full_name='CurrencyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EUR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHF', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=188,
  serialized_end=229,
)
_sym_db.RegisterEnumDescriptor(_CURRENCYTYPE)

CurrencyType = enum_type_wrapper.EnumTypeWrapper(_CURRENCYTYPE)
PLN = 0
EUR = 1
CHF = 2



_SUBSCRIBEDCURRENCIES = _descriptor.Descriptor(
  name='SubscribedCurrencies',
  full_name='SubscribedCurrencies',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nativeCurrency', full_name='SubscribedCurrencies.nativeCurrency', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='foreignCurrencies', full_name='SubscribedCurrencies.foreignCurrencies', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=121,
)


_CURRENCYVALUE = _descriptor.Descriptor(
  name='CurrencyValue',
  full_name='CurrencyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='CurrencyValue.currency', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='CurrencyValue.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=186,
)

_SUBSCRIBEDCURRENCIES.fields_by_name['nativeCurrency'].enum_type = _CURRENCYTYPE
_SUBSCRIBEDCURRENCIES.fields_by_name['foreignCurrencies'].enum_type = _CURRENCYTYPE
_CURRENCYVALUE.fields_by_name['currency'].enum_type = _CURRENCYTYPE
DESCRIPTOR.message_types_by_name['SubscribedCurrencies'] = _SUBSCRIBEDCURRENCIES
DESCRIPTOR.message_types_by_name['CurrencyValue'] = _CURRENCYVALUE
DESCRIPTOR.enum_types_by_name['CurrencyType'] = _CURRENCYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribedCurrencies = _reflection.GeneratedProtocolMessageType('SubscribedCurrencies', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEDCURRENCIES,
  __module__ = 'currency_pb2'
  # @@protoc_insertion_point(class_scope:SubscribedCurrencies)
  ))
_sym_db.RegisterMessage(SubscribedCurrencies)

CurrencyValue = _reflection.GeneratedProtocolMessageType('CurrencyValue', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCYVALUE,
  __module__ = 'currency_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyValue)
  ))
_sym_db.RegisterMessage(CurrencyValue)



_CURRENCY = _descriptor.ServiceDescriptor(
  name='Currency',
  full_name='Currency',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=231,
  serialized_end=306,
  methods=[
  _descriptor.MethodDescriptor(
    name='DownloadCurrencies',
    full_name='Currency.DownloadCurrencies',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEDCURRENCIES,
    output_type=_CURRENCYVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCY)

DESCRIPTOR.services_by_name['Currency'] = _CURRENCY

# @@protoc_insertion_point(module_scope)
